//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//介绍：基于表Base_RoleInfo,获取delflag=0的两个字段：RoleName,RoleKey，弄成对应的“编译时动态” 的枚举
//		在编程的时候，程序开发人员只需要关注RoleKey字段的值即可
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HRL.Model.Enums
{
    /// <summary>
    /// 角色，要与数据库角色表记录一一对应
    /// </summary>
    public enum Role
    {
		/// <summary>
        /// 单位领导 
        /// </summary>
		[Description("单位领导")]
		r_leaderOfCompany,
		/// <summary>
        /// 区领导 
        /// </summary>
		[Description("区领导")]
		r_leaderOfDistict,
		/// <summary>
        /// 普通个人 
        /// </summary>
		[Description("普通个人")]
		r_ordPer,
		/// <summary>
        /// 系统管理员 
        /// </summary>
		[Description("系统管理员")]
		r_systemManager,
	}
}