//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

 
using HRL.Model;
namespace HRL.IDAL
{
	
	public partial interface IBase_DeptInfoRepository : IBaseRepository<Base_DeptInfo> { }	
	public partial interface IBase_MenuInfoRepository : IBaseRepository<Base_MenuInfo> { }	
	public partial interface IBase_RoleMenuInfoRepository : IBaseRepository<Base_RoleMenuInfo> { }	
	public partial interface IBase_RolesInfoRepository : IBaseRepository<Base_RolesInfo> { }	
	public partial interface IBase_UserInfoRepository : IBaseRepository<Base_UserInfo> { }	
	public partial interface IBase_UserMenuInfoRepository : IBaseRepository<Base_UserMenuInfo> { }	
	public partial interface IBase_UserRoleInfoRepository : IBaseRepository<Base_UserRoleInfo> { }	
	public partial interface IBus_EffciencyComplainRepository : IBaseRepository<Bus_EffciencyComplain> { }	
	public partial interface IBus_EffComplExeResRepository : IBaseRepository<Bus_EffComplExeRes> { }	
	public partial interface IBus_TakeErrorRepository : IBaseRepository<Bus_TakeError> { }	
	public partial interface IBus_TakeErrorAttributeRepository : IBaseRepository<Bus_TakeErrorAttribute> { }	
	public partial interface ISys_LanguageTypeRepository : IBaseRepository<Sys_LanguageType> { }	
	public partial interface ISys_MultiLangInfoRepository : IBaseRepository<Sys_MultiLangInfo> { }	
	public partial interface ISys_ProvincesRepository : IBaseRepository<Sys_Provinces> { }
}