//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using HRL.IDAL;
using System.Data.Entity;
using System.Data.SqlClient;
namespace HRL.DAL
{
    public partial class  DbSession : IDbSession
	{
			   
		private IBase_DeptInfoRepository _Base_DeptInfoRepository;
		public IBase_DeptInfoRepository Base_DeptInfoRepository
		{
			get
			{
				if (_Base_DeptInfoRepository == null)
				{
					_Base_DeptInfoRepository = new Base_DeptInfoRepository();
				}
				return _Base_DeptInfoRepository;
			}
			set
			{
				_Base_DeptInfoRepository = value;
			}
		}	   
		private IBase_MenuInfoRepository _Base_MenuInfoRepository;
		public IBase_MenuInfoRepository Base_MenuInfoRepository
		{
			get
			{
				if (_Base_MenuInfoRepository == null)
				{
					_Base_MenuInfoRepository = new Base_MenuInfoRepository();
				}
				return _Base_MenuInfoRepository;
			}
			set
			{
				_Base_MenuInfoRepository = value;
			}
		}	   
		private IBase_RoleMenuInfoRepository _Base_RoleMenuInfoRepository;
		public IBase_RoleMenuInfoRepository Base_RoleMenuInfoRepository
		{
			get
			{
				if (_Base_RoleMenuInfoRepository == null)
				{
					_Base_RoleMenuInfoRepository = new Base_RoleMenuInfoRepository();
				}
				return _Base_RoleMenuInfoRepository;
			}
			set
			{
				_Base_RoleMenuInfoRepository = value;
			}
		}	   
		private IBase_RolesInfoRepository _Base_RolesInfoRepository;
		public IBase_RolesInfoRepository Base_RolesInfoRepository
		{
			get
			{
				if (_Base_RolesInfoRepository == null)
				{
					_Base_RolesInfoRepository = new Base_RolesInfoRepository();
				}
				return _Base_RolesInfoRepository;
			}
			set
			{
				_Base_RolesInfoRepository = value;
			}
		}	   
		private IBase_UserInfoRepository _Base_UserInfoRepository;
		public IBase_UserInfoRepository Base_UserInfoRepository
		{
			get
			{
				if (_Base_UserInfoRepository == null)
				{
					_Base_UserInfoRepository = new Base_UserInfoRepository();
				}
				return _Base_UserInfoRepository;
			}
			set
			{
				_Base_UserInfoRepository = value;
			}
		}	   
		private IBase_UserMenuInfoRepository _Base_UserMenuInfoRepository;
		public IBase_UserMenuInfoRepository Base_UserMenuInfoRepository
		{
			get
			{
				if (_Base_UserMenuInfoRepository == null)
				{
					_Base_UserMenuInfoRepository = new Base_UserMenuInfoRepository();
				}
				return _Base_UserMenuInfoRepository;
			}
			set
			{
				_Base_UserMenuInfoRepository = value;
			}
		}	   
		private IBase_UserRoleInfoRepository _Base_UserRoleInfoRepository;
		public IBase_UserRoleInfoRepository Base_UserRoleInfoRepository
		{
			get
			{
				if (_Base_UserRoleInfoRepository == null)
				{
					_Base_UserRoleInfoRepository = new Base_UserRoleInfoRepository();
				}
				return _Base_UserRoleInfoRepository;
			}
			set
			{
				_Base_UserRoleInfoRepository = value;
			}
		}	   
		private IBus_EffciencyComplainRepository _Bus_EffciencyComplainRepository;
		public IBus_EffciencyComplainRepository Bus_EffciencyComplainRepository
		{
			get
			{
				if (_Bus_EffciencyComplainRepository == null)
				{
					_Bus_EffciencyComplainRepository = new Bus_EffciencyComplainRepository();
				}
				return _Bus_EffciencyComplainRepository;
			}
			set
			{
				_Bus_EffciencyComplainRepository = value;
			}
		}	   
		private IBus_EffComplExeResRepository _Bus_EffComplExeResRepository;
		public IBus_EffComplExeResRepository Bus_EffComplExeResRepository
		{
			get
			{
				if (_Bus_EffComplExeResRepository == null)
				{
					_Bus_EffComplExeResRepository = new Bus_EffComplExeResRepository();
				}
				return _Bus_EffComplExeResRepository;
			}
			set
			{
				_Bus_EffComplExeResRepository = value;
			}
		}	   
		private IBus_TakeErrorRepository _Bus_TakeErrorRepository;
		public IBus_TakeErrorRepository Bus_TakeErrorRepository
		{
			get
			{
				if (_Bus_TakeErrorRepository == null)
				{
					_Bus_TakeErrorRepository = new Bus_TakeErrorRepository();
				}
				return _Bus_TakeErrorRepository;
			}
			set
			{
				_Bus_TakeErrorRepository = value;
			}
		}	   
		private IBus_TakeErrorAttributeRepository _Bus_TakeErrorAttributeRepository;
		public IBus_TakeErrorAttributeRepository Bus_TakeErrorAttributeRepository
		{
			get
			{
				if (_Bus_TakeErrorAttributeRepository == null)
				{
					_Bus_TakeErrorAttributeRepository = new Bus_TakeErrorAttributeRepository();
				}
				return _Bus_TakeErrorAttributeRepository;
			}
			set
			{
				_Bus_TakeErrorAttributeRepository = value;
			}
		}	   
		private ISys_LanguageTypeRepository _Sys_LanguageTypeRepository;
		public ISys_LanguageTypeRepository Sys_LanguageTypeRepository
		{
			get
			{
				if (_Sys_LanguageTypeRepository == null)
				{
					_Sys_LanguageTypeRepository = new Sys_LanguageTypeRepository();
				}
				return _Sys_LanguageTypeRepository;
			}
			set
			{
				_Sys_LanguageTypeRepository = value;
			}
		}	   
		private ISys_MultiLangInfoRepository _Sys_MultiLangInfoRepository;
		public ISys_MultiLangInfoRepository Sys_MultiLangInfoRepository
		{
			get
			{
				if (_Sys_MultiLangInfoRepository == null)
				{
					_Sys_MultiLangInfoRepository = new Sys_MultiLangInfoRepository();
				}
				return _Sys_MultiLangInfoRepository;
			}
			set
			{
				_Sys_MultiLangInfoRepository = value;
			}
		}	   
		private ISys_ProvincesRepository _Sys_ProvincesRepository;
		public ISys_ProvincesRepository Sys_ProvincesRepository
		{
			get
			{
				if (_Sys_ProvincesRepository == null)
				{
					_Sys_ProvincesRepository = new Sys_ProvincesRepository();
				}
				return _Sys_ProvincesRepository;
			}
			set
			{
				_Sys_ProvincesRepository = value;
			}
		}
	}
}