//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

 
using HRL.Model;
using HRL.IDAL;
namespace HRL.DAL
{ 
	 
	public partial class Base_DeptInfoRepository : BaseRepository<Base_DeptInfo>, IBase_DeptInfoRepository { }
	 
	public partial class Base_MenuInfoRepository : BaseRepository<Base_MenuInfo>, IBase_MenuInfoRepository { }
	 
	public partial class Base_RoleMenuInfoRepository : BaseRepository<Base_RoleMenuInfo>, IBase_RoleMenuInfoRepository { }
	 
	public partial class Base_RolesInfoRepository : BaseRepository<Base_RolesInfo>, IBase_RolesInfoRepository { }
	 
	public partial class Base_UserInfoRepository : BaseRepository<Base_UserInfo>, IBase_UserInfoRepository { }
	 
	public partial class Base_UserMenuInfoRepository : BaseRepository<Base_UserMenuInfo>, IBase_UserMenuInfoRepository { }
	 
	public partial class Base_UserRoleInfoRepository : BaseRepository<Base_UserRoleInfo>, IBase_UserRoleInfoRepository { }
	 
	public partial class Bus_EffciencyComplainRepository : BaseRepository<Bus_EffciencyComplain>, IBus_EffciencyComplainRepository { }
	 
	public partial class Bus_EffComplExeResRepository : BaseRepository<Bus_EffComplExeRes>, IBus_EffComplExeResRepository { }
	 
	public partial class Bus_TakeErrorRepository : BaseRepository<Bus_TakeError>, IBus_TakeErrorRepository { }
	 
	public partial class Bus_TakeErrorAttributeRepository : BaseRepository<Bus_TakeErrorAttribute>, IBus_TakeErrorAttributeRepository { }
	 
	public partial class Sys_LanguageTypeRepository : BaseRepository<Sys_LanguageType>, ISys_LanguageTypeRepository { }
	 
	public partial class Sys_MultiLangInfoRepository : BaseRepository<Sys_MultiLangInfo>, ISys_MultiLangInfoRepository { }
	 
	public partial class Sys_ProvincesRepository : BaseRepository<Sys_Provinces>, ISys_ProvincesRepository { }
}