//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserInfo
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string Email { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string Phone { get; set; }
        public string Addrs { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string DeptId { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Bz { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modified { get; set; }
    }
}
