//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_TakeError
    {
        public string ID { get; set; }
        public string FromSource { get; set; }
        public string ActionId { get; set; }
        public string TypeVal { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ResCompany { get; set; }
        public string ResCompanyId { get; set; }
        public string ResPerson { get; set; }
        public string AttributeID { get; set; }
        public string AccessCompany { get; set; }
        public string AccessCompanyId { get; set; }
        public Nullable<System.DateTime> OkTime { get; set; }
        public Nullable<int> IsOverTime { get; set; }
        public Nullable<int> IsSearch { get; set; }
        public string OverQuality { get; set; }
        public string Remark { get; set; }
        public Nullable<int> LevelRecords { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string UserId { get; set; }
        public Nullable<int> IsPass { get; set; }
    }
}
