//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_EffciencyComplain
    {
        public string ID { get; set; }
        public string CompanyInfo { get; set; }
        public string CompanyInfoId { get; set; }
        public string CompanyPerId { get; set; }
        public string OtherPer { get; set; }
        public string ComplainFrmSourceId { get; set; }
        public Nullable<System.DateTime> ComplainAcceptTime { get; set; }
        public string ComplainCode { get; set; }
        public string ComplainProfileContent { get; set; }
        public string AboutFile { get; set; }
        public string ComplainType { get; set; }
        public string ExecuteRes { get; set; }
        public Nullable<int> IsOverTime { get; set; }
        public Nullable<int> IsSearch { get; set; }
        public Nullable<int> MassesSatisfy { get; set; }
        public Nullable<int> LevelRecords { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Modified { get; set; }
        public string UserId { get; set; }
        public Nullable<int> IsPass { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string AreaCode { get; set; }
        public string ComplainTel { get; set; }
        public string ComplainAreaCode { get; set; }
    }
}
