//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Provinces
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public string CityEnglishName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ParentPath { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> IsUse { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
