//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LanguageType
    {
        public string Id { get; set; }
        public string LanName { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public string LanDesc { get; set; }
    }
}
