//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_MultiLangInfo
    {
        public string ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string TABLE_DESC { get; set; }
        public string COLUMN_NAME { get; set; }
        public string COLUMN_ID { get; set; }
        public Nullable<int> ORDERBY { get; set; }
        public string COLUMN_CULTURE { get; set; }
    }
}
